
project: teller

# Set this if you want to carry over parent process' environment variables
# carry_env: true 


#
# Variables
#
# Feel free to add options here to be used as a variable throughout
# paths.
#
opts:
  region: env:AWS_REGION    # you can get env variables with the 'env:' prefix
  stage: development


#
# Providers
#
providers:
  # Configure via environment:
  # CONSUL_HTTP_ADDR
  dotenv:
    env:
      FOO:
        path: ~/my-dot-env.env

